---
- hosts: all
  tasks:
  - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
  
  - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        
  - name: "Install Docker"
    package:
      name: "docker-ce"
      state: "latest"

  - name: "Install Docker-compose"
    package:
      name: "docker-compose"
      state: "latest"

  - name: "Start Docker service"
    service:
      name: "docker"
      state: "started"
      enabled: "yes"

  - name: "Install Git"
    package:
      name: "git"
      state: "latest"

  - name: "Install Make"
    package:
      name: "make"
      state: "latest"

  - name: "Clone repo number2"
    git:
      repo: "https://github.com/strokin-ivan/number2.git"
      dest: "/home/$USER/repos"
      clone: yes
      update: yes

  - name: "Makefile run"
    make:
    chdir: /home/$USER/repos
      target: run

  - name: "Add user to docker group"
    user:
      name: "$USER"
      groups: "docker"
      append: "yes"
...
